.Dd August 4, 2022
.Dt WAYCOPY 1
.Os
.Sh NAME
.Nm waycopy
.Nd copy data to the clipboard
.Sh SYNOPSIS
.Nm
.Op Fl p
.Op Fl s Ar seat
.Op Fl t Ar mimetype
.Sh DESCRIPTION
.Nm
copies data from standard in to the clipboard using the wlr-data-control
Wayland extension protocol.
.Bl -tag -width Ds
.It Fl p
Use primary clipboard
.It Fl s Ar seat
The name of the seat to use
.Po
defaults to the first seat sent by the compositor
.Pc
.It Fl t Ar mimetype
The mimetype of the data
.Po
defaults to "text/plain;charset=utf-8"
.Pc
.El
.Sh AUTHORS
.An Nihal Jere Aq Mt nihal@nihaljere.xyz
